---
galaxy_info:
  role_name: apt
  author: homelab
  description: Updates and upgrades apt packages
  license: MIT
  min_ansible_version: "2.14"
  platforms:
    - name: Ubuntu
      versions:
        - all
  galaxy_tags:
    - system
    - apt
    - ubuntu
dependencies: []
